import Link from 'next/link'

export const metadata = {
  title: 'Terms and Conditions — SKDL',
  description: 'Terms of Use for SKDL media delivery service.',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white pt-10 md:pt-16 pb-16 px-4 md:px-8 font-sans selection:bg-white/20">
      <div className="max-w-3xl mx-auto space-y-12">
        <header className="space-y-4">
          <Link href="/" className="text-zinc-500 hover:text-[#e8ff47] transition-colors text-xs font-mono tracking-widest uppercase">
            &larr; Return Home
          </Link>
          <h1 className="text-4xl md:text-6xl font-space font-bold tracking-tighter uppercase underline decoration-white/10">
            Terms of Use
          </h1>
          <p className="text-zinc-500 font-mono text-xs uppercase tracking-widest">
            Effective: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </header>

        <section className="space-y-10 text-zinc-400 text-sm md:text-base leading-relaxed font-mono">
          <div className="space-y-4">
            <h2 className="text-white text-xl font-space uppercase tracking-tight">01. Use of Service</h2>
            <p>
              SKDL (@SK_DLBOT) is provided as an AI interface for discovering media metadata and delivering 
              requested files. You use this service at your own risk.
            </p>
          </div>

          <div className="space-y-4 border-l border-white/5 pl-6">
            <h2 className="text-white text-xl font-space uppercase tracking-tight">02. Expiration Policy</h2>
            <p>
              All links generated by the bot are temporary and valid for 6 hours only. We do not provide long-term 
              hosting and links will not be re-generated for expired sessions automatically.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-white text-xl font-space uppercase tracking-tight">03. Acceptance of Terms</h2>
            <p>
              By sending a request to @SK_DLBOT or visiting this domain, you agree to these terms. 
              We reserve the right to limit access to our services if we detect automated abuse 
              or usage that exceeds our fair-use rate limits.
            </p>
          </div>

          <div className="space-y-4 border-l border-white/5 pl-6 bg-white/5 p-6 rounded-sm">
            <h2 className="text-white text-xl font-space uppercase tracking-tight">04. Limitation of Liability</h2>
            <p>
              SKDL and its creators share no responsibility for the content requested or the usage of the links 
              beyond their primary delivery function. We do not host the files directly; we only provide 
              AI-powered indexing and retrieval.
            </p>
          </div>
        </section>

        <footer className="pt-12 border-t border-white/10 text-zinc-600 text-[10px] uppercase font-mono tracking-[0.2em] text-center">
          SKDL // samkiel.online
        </footer>
      </div>
    </main>
  )
}
